export const NUEVO_PRODUCTO          = "NUEVO_PRODUCTO";
export const NUEVO_PRODUCTO_ERROR    = "NUEVO_PRODUCTO_ERROR";
export const NUEVO_PRODUCTO_CORRECTO = "NUEVO_PRODUCTO_CORRECTO";

export const DESCARGAR_PRODUCTO = "DESCARGAR_PRODUCTO";
export const DESCARGAR_PRODUCTO_ERROR = "DESCARGAR_PRODUCTO_ERROR";
export const DESCARGAR_PRODUCTO_CORRECTO = "DESCARGAR_PRODUCTO_CORRECTO";