export const NUEVO_PRODUCTO          = "NUEVO_PRODUCTO";
export const NUEVO_PRODUCTO_ERROR    = "NUEVO_PRODUCTO_ERROR";
export const NUEVO_PRODUCTO_CORRECTO = "NUEVO_PRODUCTO_CORRECTO";

export const DESCARGAR_PRODUCTO = "DESCARGAR_PRODUCTO";
export const DESCARGAR_PRODUCTO_ERROR = "DESCARGAR_PRODUCTO_ERROR";
export const DESCARGAR_PRODUCTO_CORRECTO = "DESCARGAR_PRODUCTO_CORRECTO";

export const BORRAR_PRODUCTO = "BORRAR_PRODUCTO";
export const BORRAR_PRODUCTO_ERROR = "BORRAR_PRODUCTO_ERROR";
export const BORRAR_PRODUCTO_CORRECTO = "BORRAR_PRODUCTO_CORRECTO";

export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
export const EDITAR_PRODUCTO_INICIAR = "EDITAR_PRODUCTO_INICIAR";
export const EDITAR_PRODUCTO_ERROR = "EDITAR_PRODUCTO_ERROR";
export const EDITAR_PRODUCTO_CORRECTO = "EDITAR_PRODUCTO_CORRECTO";